string name                                # The name of the population
string neuron_model                        # The neuron model used in this population
cle_ros_msgs/NeuronParameter[] parameters  # Neuron parameters
int64[] gids                               # The global unique identifiers of the neurons contained in this population
int64[] indices                            # The population neuron indexes