---
string brain_type   # Type of the brain (currently "py" or "h5"
string brain_data   # Brain data field
string data_type    # Type of data in brain_data: text or base64
string brain_populations # Type of the brain populations: json
